### ISSUE TITLE
expect error when failed to deploy, but the result is success

### ISSUE THREAD

**Issue by YutoUrakami** [loilo-inc/actions-deploy-cage#2]
actions was passed when failed to deploy

![スクリーンショット 2019-12-09 15 55 59](https://user-images.githubusercontent.com/21374754/70414170-9f6a8500-1a9c-11ea-94d9-44a25076831a.png)

**Comment by juri-t** [comment]
fix https://github.com/loilo-inc/actions-deploy-cage/commit/7a3712ab9bef5be238b05a2d985a78edb9bbaa0c
